# 公共配置文件
spring:
  application:
    name: bsoj-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
#    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bsoj
    username: root
    password: zxrwyt
  # Redis 配置
  # todo 需替换配置，然后取消注释
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8121
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# minio 配置
minio:
  # 这个一定要写API的访问地址，而不是控制台的，否则会报错！！！
  endpoint: http://8.138.10.224:9121
  accessKey: minio_root
  secretKey: minio_k3kg8s.@sc9
#  静态资源访问路径
  bucketName: bsoj-image
  # 拼接路径
  url: ${endpoint}/${bucketName}/


# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 代码沙箱配置
codesandbox:
  type: remote

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

# AI 配置
ai:
  apiKey: 4b4c786890ed43aeb65547fd04dabee3.cnYBXFhDmxcAmIXj